package utils

const SHOW_COLLECTION = "show"
const USER_COLLECTION = "user"

const APPLICATION_PORT = "APPLICATION_PORT"
const SITE_KEY = "SITE_KEY"
const ALLOWED_ORIGINS = "ALLOWED_ORIGINS"
const FIRESTORE_EMULATOR_HOST = "FIRESTORE_EMULATOR_HOST"
const GCP_PROJECT_ID = "GCP_PROJECT_ID"

const LOCALHOST = "localhost"
const FIRESTORE_EMULATOR_PORT = "5050"
